"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
try:
    import tomllib
except ImportError:
    import tomli as tomllib

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-77s@l!7^nner#5%q^-6k*+n04a!hpa5_+j69pv$16@#e6fb)6b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # My applications
    'users.apps.UsersConfig',
    'subscriptions.apps.SubscriptionsConfig',
    'news.apps.NewsConfig',
    'core.apps.CoreConfig',
]

AUTH_USER_MODEL = 'users.User' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

###
# --- Email Settings ---
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'YOUR_EMAIL@gmail.com'
# EMAIL_HOST_PASSWORD = 'YOUR_APP_PASSWORD'

DEFAULT_FROM_EMAIL = 'webmaster@yynet.org'
EMAIL_HOST = 'yynet.org'

LOGIN_URL = 'users:login'

SITE_ID = 1 # どのサイト設定を使うかを指定

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(name)s:%(lineno)s %(funcName)s:%(levelname)s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Load API keys from .secrets.toml
SECRETS_FILE = BASE_DIR / 'config' / '.secrets.toml'

# config/.secrets.toml の設定例
# --- 必須 ---
# どちらか、あるいは両方のAPIキーを設定
# GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
# OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
#
# --- オプション ---
# AIモデル名を指定（指定しない場合はデフォルト値が使われます）
# GEMINI_MODEL = "gemini-pro-latest"
# OPENAI_MODEL = "gpt-4o"
#
# OpenAI互換APIを利用する場合に指定
# OPENAI_API_BASE_URL = "https://your-openai-compatible-api.example.com/v1"
#
# オンプレミス環境などでSSL証明書の検証を無効にする場合に指定
# OPENAI_SSL_VERIFY = false
if SECRETS_FILE.exists():
    with open(SECRETS_FILE, 'rb') as f:
        secrets = tomllib.load(f)
    GEMINI_API_KEY = secrets.get('GEMINI_API_KEY')
    OPENAI_API_KEY = secrets.get('OPENAI_API_KEY')
    # AIモデルとURLを .secrets.toml から読み込む（デフォルト値付き）
    GEMINI_MODEL = secrets.get('GEMINI_MODEL', 'gemini-pro-latest')
    OPENAI_MODEL = secrets.get('OPENAI_MODEL', 'gpt-4o')
    OPENAI_API_BASE_URL = secrets.get('OPENAI_API_BASE_URL') # デフォルトはNone
    OPENAI_SSL_VERIFY = secrets.get('OPENAI_SSL_VERIFY', True)
else:
    GEMINI_API_KEY = None
    OPENAI_API_KEY = None
    GEMINI_MODEL = 'gemini-pro-latest'
    OPENAI_MODEL = 'gpt-4o'
    OPENAI_API_BASE_URL = None
    OPENAI_SSL_VERIFY = True
